### ISSUE TITLE
Call to flashState in streammenu.py fails

### ISSUE THREAD

**Issue by acourt** [Motsai/neblina-python#71]
``` >>flashState
Traceback (most recent call last):
  File ".\streammenu.py", line 390, in <module>
    console . cmdloop()
  File ".\streammenu.py", line 90, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "C:\Python35\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Python35\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File ".\streammenu.py", line 265, in do_flashState
    state = self.comm.flashGetState()
  File "C:\Users\Alex\Documents\GitHub\neblina-python\neblinaAPI.py", line 217, in flashGetState
    return MotAndFlashRecStateData.recorderStatusStrings[packet.data.recorderStatus]
NameError: name 'MotAndFlashRecStateData' is not defined
```

**Comment by souellet-ms** [comment]
Fixed
